export const styles = {
    paper:{
        background:"#f1f4f3",
        my:"10px"
    },
    head:{
        display:"flex",
        justifyContent:"center",
        mt:"20px",
        fontSize:"28px"
    },
    box:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        my:"20px"
    },
    input:{
        mx:"10px",
        background:"white",
    },
    btn:{
        mx:"15px",
        background:"#edf6ff",
        borderRadius: "20px"
    },
    chkBox:{
        mx:"10px",
        display:"flex",
        flexDirection:"column",
        justifyContent:"center",
    }
};