export const styles = {
  head:{
    fontSize:"28px",
    display:"flex",
    justifyContent:"center",
    my:"7px"
  },
  paper:{
    m:"4px",
    borderRadius:"30px",
    background:"#d0e2e4",
    cursor:"pointer",
    '&:hover':{
      background:"#e1eaec",
  }
  },
  paperA:{
    m:"4px",
    borderRadius:"30px",
    background:"#abdae4"
  },
  flex:{
    display:"flex",
        alignItems:"center",
        justifyContent:"start",
        alignItems:"center",
        pl:"30px",
        my:"10px"
  },
  name:{
    fontSize:"20px",
    width:"60%"
  },
  class:{
    fontSize:"17px",
    width:"60%",
    color:"#535353"
  }
};
